#!/usr/bin/env python3
"""
Self-contained bypass-strategy generator.

Builds candidate winws.exe command lines from known dpi-desync methods
(the same building blocks already used across this project's general*.bat
strategies), tests each candidate through zapret_tester's existing
connectivity checks (test_one_strategy), and returns the best-performing
one(s). No user interaction with individual --dpi-desync-* flags required —
this is the "just find something that works" counterpart to manually picking
a strategy.

Two modes:
  - "simple":   one method applied uniformly to all 5 variable filter
                sections (hostlist AND ipset sections use the same method).
                Fast, covers the common case (like general (ALT)/(ALT2)/...).
  - "advanced": hostlist-based sections (Discord/Google/general lists) and
                ipset-based sections (the catch-all IP list) may use
                DIFFERENT methods — mirrors how general (ALT5)/(ALT7) are
                actually built in this project. Runs a two-stage search:
                stage 1 surveys method combinations, stage 2 refines
                fooling/cutoff around the best stage-1 result(s).

Generated candidates are written to a temporary .bat inside the version
folder (so relative %BIN%/%LISTS% paths and the service.bat calls at the top
resolve exactly like a normal strategy file), tested via
zapret_tester.test_one_strategy(), then deleted. A winning candidate can
afterwards be persisted permanently with save_candidate() or installed
directly as the 'zapret' service.

Before trying any candidate, run_generator() also measures a BASELINE: the
same connectivity checks with no bypass running at all (winws killed). This
exists because "every candidate scores 4/4" is ambiguous — it can mean every
method genuinely defeats the censor, or it can mean these targets simply
aren't blocked on this network right now (in which case no method proved
anything). Comparing every candidate's score to the baseline lets the caller
tell those two cases apart instead of the person having to manually run curl
with winws stopped to check.
"""

import time
import uuid
from pathlib import Path

import zapret_tester as zt
from i18n import t

# --------------------------------------------------------------------------- #
# fixed building blocks — identical across (almost) every strategy in this
# project, so they are never part of the search space
# --------------------------------------------------------------------------- #

IPSET_EXCL = ('--ipset-exclude="%LISTS%ipset-exclude.txt" '
              '--ipset-exclude="%LISTS%ipset-exclude-user.txt"')
HOSTLIST_EXCL = ('--hostlist-exclude="%LISTS%list-exclude.txt" '
                 '--hostlist-exclude="%LISTS%list-exclude-user.txt"')

FIXED_HEAD = (
    '@echo off\n'
    'chcp 65001 > nul\n'
    ':: 65001 - UTF-8\n'
    ':: auto-generated by zapret_generator.py\n\n'
    'cd /d "%~dp0"\n'
    'call service.bat status_zapret\n'
    'call service.bat check_updates\n'
    'call service.bat load_game_filter\n'
    'call service.bat load_user_lists\n'
    'echo:\n\n'
    'set "BIN=%~dp0bin\\"\n'
    'set "LISTS=%~dp0lists\\"\n'
    'cd /d %BIN%\n\n'
)

FIXED_QUIC = (
    '--filter-udp=443 --hostlist="%LISTS%list-general.txt" '
    '--hostlist="%LISTS%list-general-user.txt" ' + HOSTLIST_EXCL + ' ' + IPSET_EXCL +
    ' --dpi-desync=fake --dpi-desync-repeats=6 '
    '--dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin"'
)
FIXED_DISCORD_VOICE = (
    '--filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun '
    '--dpi-desync=fake --dpi-desync-fake-discord="%BIN%quic_initial_dbankcloud_ru.bin" '
    '--dpi-desync-fake-stun="%BIN%quic_initial_dbankcloud_ru.bin" --dpi-desync-repeats=6'
)
FIXED_QUIC_IPSET = (
    '--filter-udp=443 --ipset="%LISTS%ipset-all.txt" ' + HOSTLIST_EXCL + ' ' + IPSET_EXCL +
    ' --dpi-desync=fake --dpi-desync-repeats=6 '
    '--dpi-desync-fake-quic="%BIN%quic_initial_www_google_com.bin"'
)


def _udp_fallback(repeats=12, cutoff="n2"):
    return (f'--filter-udp=%GameFilterUDP% --ipset="%LISTS%ipset-all.txt" {IPSET_EXCL} '
            f'--dpi-desync=fake --dpi-desync-repeats={repeats} --dpi-desync-any-protocol=1 '
            f'--dpi-desync-fake-unknown-udp="%BIN%quic_initial_dbankcloud_ru.bin" '
            f'--dpi-desync-cutoff={cutoff}')


def _core_slot(filter_part, match, method_str, extra_http=False):
    tail = ' --dpi-desync-fake-http="%BIN%tls_clienthello_max_ru.bin"' if extra_http else ""
    return f'{filter_part} {match} {method_str}{tail}'


def _assemble(name, slots):
    body = " --new ^\n".join(slots)
    cmd = (f'start "zapret: {name}" /min "%BIN%winws.exe" '
           f'--wf-tcp=80,443,2053,2083,2087,2096,8443,%GameFilterTCP% '
           f'--wf-udp=443,19294-19344,50000-50100,%GameFilterUDP% ^\n{body}\n')
    return FIXED_HEAD + cmd


def build_bat_text(name: str, method_str: str, *, game_cutoff="n3",
                    udp_repeats=12, udp_cutoff="n2") -> str:
    """'simple' mode: one method_str applied to all 5 variable slots."""
    slots = [
        FIXED_QUIC,
        FIXED_DISCORD_VOICE,
        _core_slot('--filter-tcp=2053,2083,2087,2096,8443', '--hostlist-domains=discord.media', method_str),
        _core_slot('--filter-tcp=443', '--hostlist="%LISTS%list-google.txt" --ip-id=zero', method_str),
        _core_slot(
            '--filter-tcp=80,443',
            f'--hostlist="%LISTS%list-general.txt" --hostlist="%LISTS%list-general-user.txt" {HOSTLIST_EXCL} {IPSET_EXCL}',
            method_str, extra_http=True,
        ),
        FIXED_QUIC_IPSET,
        _core_slot(
            '--filter-tcp=80,443,8443',
            f'--ipset="%LISTS%ipset-all.txt" {HOSTLIST_EXCL} {IPSET_EXCL}',
            method_str, extra_http=True,
        ),
        _core_slot(
            '--filter-tcp=%GameFilterTCP%',
            f'--ipset="%LISTS%ipset-all.txt" {IPSET_EXCL}',
            f'{method_str} --dpi-desync-any-protocol=1 --dpi-desync-cutoff={game_cutoff}',
            extra_http=True,
        ),
        _udp_fallback(udp_repeats, udp_cutoff),
    ]
    return _assemble(name, slots)


def build_bat_text_split(name: str, hostlist_method: str, ipset_method: str, *,
                          game_cutoff="n3", udp_repeats=12, udp_cutoff="n2") -> str:
    """'advanced' mode: hostlist-based slots (3/4/5) and ipset-based slots
    (7/8) may use different methods."""
    slots = [
        FIXED_QUIC,
        FIXED_DISCORD_VOICE,
        _core_slot('--filter-tcp=2053,2083,2087,2096,8443', '--hostlist-domains=discord.media', hostlist_method),
        _core_slot('--filter-tcp=443', '--hostlist="%LISTS%list-google.txt" --ip-id=zero', hostlist_method),
        _core_slot(
            '--filter-tcp=80,443',
            f'--hostlist="%LISTS%list-general.txt" --hostlist="%LISTS%list-general-user.txt" {HOSTLIST_EXCL} {IPSET_EXCL}',
            hostlist_method, extra_http=True,
        ),
        FIXED_QUIC_IPSET,
        _core_slot(
            '--filter-tcp=80,443,8443',
            f'--ipset="%LISTS%ipset-all.txt" {HOSTLIST_EXCL} {IPSET_EXCL}',
            ipset_method, extra_http=True,
        ),
        _core_slot(
            '--filter-tcp=%GameFilterTCP%',
            f'--ipset="%LISTS%ipset-all.txt" {IPSET_EXCL}',
            f'{ipset_method} --dpi-desync-any-protocol=1 --dpi-desync-cutoff={game_cutoff}',
            extra_http=True,
        ),
        _udp_fallback(udp_repeats, udp_cutoff),
    ]
    return _assemble(name, slots)


# --------------------------------------------------------------------------- #
# SIMPLE mode search space — one curated method per candidate, each drawn
# from a distinct family already proven in this project's own strategies
# --------------------------------------------------------------------------- #

SIMPLE_SPACE = [
    ("simple_multisplit",
     'multisplit --dpi-desync-split-seqovl=681 --dpi-desync-split-pos=1 '
     '--dpi-desync-split-seqovl-pattern="%BIN%tls_clienthello_www_google_com.bin"'),
    ("simple_hostfakesplit",
     'hostfakesplit --dpi-desync-repeats=4 --dpi-desync-fooling=ts '
     '--dpi-desync-hostfakesplit-mod=host=www.google.com'),
    ("simple_fakedsplit",
     'fake,fakedsplit --dpi-desync-repeats=6 --dpi-desync-fooling=ts '
     '--dpi-desync-fakedsplit-pattern=0x00 --dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"'),
    ("simple_fake_plain",
     'fake --dpi-desync-repeats=6 --dpi-desync-fooling=ts '
     '--dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"'),
    ("simple_multidisorder",
     'fake,multidisorder --dpi-desync-split-pos=1,midsld --dpi-desync-repeats=11 '
     '--dpi-desync-fooling=badseq --dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com'),
]


# --------------------------------------------------------------------------- #
# ADVANCED mode search space — methods usable independently per slot group,
# plus a two-stage survey -> refine search
# --------------------------------------------------------------------------- #

ADV_METHODS = {
    "multisplit": 'multisplit --dpi-desync-split-seqovl=681 --dpi-desync-split-pos=1 '
                  '--dpi-desync-split-seqovl-pattern="%BIN%tls_clienthello_www_google_com.bin"',
    "fakedsplit": 'fake,fakedsplit --dpi-desync-repeats=6 --dpi-desync-fakedsplit-pattern=0x00 '
                  '--dpi-desync-fake-tls="%BIN%tls_clienthello_www_google_com.bin"',
    "multidisorder": 'fake,multidisorder --dpi-desync-split-pos=1,midsld --dpi-desync-repeats=8 '
                      '--dpi-desync-fake-tls-mod=rnd,dupsid,sni=www.google.com',
    "hostfakesplit": 'hostfakesplit --dpi-desync-repeats=4 --dpi-desync-hostfakesplit-mod=host=www.google.com',
    "syndata": 'syndata,multidisorder',
}


def _stage1_candidates():
    """Every (hostlist_key, ipset_key) pair — covers both the common case
    (same method both places) and the branching case (ALT5/ALT7-style,
    different method for hostlist vs ipset slots)."""
    keys = list(ADV_METHODS)
    for h in keys:
        for i in keys:
            yield f"adv_{h}+{i}", h, i


def _stage2_refine(hostlist_key, ipset_key):
    """Refine fooling/cutoff around a winning stage-1 method pair."""
    for fooling in ("ts", "badseq"):
        for cutoff in ("n2", "n3", "n4"):
            h_method = f"{ADV_METHODS[hostlist_key]} --dpi-desync-fooling={fooling}"
            i_method = f"{ADV_METHODS[ipset_key]} --dpi-desync-fooling={fooling}"
            name = f"adv_{hostlist_key}+{ipset_key}_refine_{fooling}_{cutoff}"
            yield name, h_method, i_method, cutoff


# --------------------------------------------------------------------------- #
# baseline (no bypass at all) — see module docstring
# --------------------------------------------------------------------------- #

def _measure_baseline(targets, log, lang):
    """Connectivity check with winws NOT running — i.e. no bypass in effect.
    If a candidate's score doesn't beat this, that candidate proved nothing:
    either the target wasn't actually blocked on this network, or the check
    itself can't detect the blocking (e.g. a bare TCP connect never sends
    the SNI that a censor resets on)."""
    zt.kill_winws()
    time.sleep(1)
    log(t(lang, "gen_baseline_start"))
    service_results = {}
    for service, hosts in targets.items():
        hits = 0
        detail = []
        for host, kind in hosts:
            ok, info, elapsed = zt.check_target(host, kind)
            detail.append((host, ok, info, elapsed))
            if ok:
                hits += 1
        service_results[service] = {"score": hits, "total": len(hosts), "detail": detail}
    for service, data in service_results.items():
        log(f"    {service:<10} {data['score']}/{data['total']}")
    return service_results


def _baseline_total(baseline):
    return sum(d["score"] for d in baseline.values())


def _is_inconclusive(baseline, overall_best):
    """True when the best candidate found didn't do any better than doing
    nothing at all — a signal that the result isn't evidence the bypass
    worked, not a signal that it worked especially well."""
    if not overall_best:
        return False
    best_total = sum(d["score"] for d in overall_best[1].values())
    return best_total <= _baseline_total(baseline)


# --------------------------------------------------------------------------- #
# test-and-record helper — shared by both modes
# --------------------------------------------------------------------------- #

def _test_candidate(version_dir: Path, bat_text: str, targets, log, lang) -> dict | None:
    tmp_path = version_dir / f"_gen_{uuid.uuid4().hex[:8]}.bat"
    tmp_path.write_text(bat_text, encoding="utf-8")
    try:
        res = zt.test_one_strategy(tmp_path, version_dir, targets=targets, log=log, lang=lang)
    finally:
        tmp_path.unlink(missing_ok=True)
    if res:
        for service, data in res.items():
            log(f"    {service:<10} {data['score']}/{data['total']}")
    return res


def _run_simple(version_dir, targets, log, should_stop, lang):
    all_results, texts = {}, {}
    total = len(SIMPLE_SPACE)
    for i, (name, method_str) in enumerate(SIMPLE_SPACE, 1):
        if should_stop():
            log(t(lang, "stopped_by_user"))
            break
        log(f"[{i}/{total}] {name}")
        bat_text = build_bat_text(name, method_str)
        res = _test_candidate(version_dir, bat_text, targets, log, lang)
        if res:
            all_results[name] = res
            texts[name] = bat_text
    return all_results, texts


def _run_advanced(version_dir, targets, log, should_stop, lang):
    all_results, texts = {}, {}

    stage1 = list(_stage1_candidates())
    log(t(lang, "gen_stage1", count=len(stage1)))
    for i, (name, hkey, ikey) in enumerate(stage1, 1):
        if should_stop():
            return all_results, texts
        log(f"[{i}/{len(stage1)}] {name}")
        bat_text = build_bat_text_split(name, ADV_METHODS[hkey], ADV_METHODS[ikey])
        res = _test_candidate(version_dir, bat_text, targets, log, lang)
        if res:
            all_results[name] = res
            texts[name] = bat_text

    if not all_results or should_stop():
        return all_results, texts

    def overall(res):
        return sum(d["score"] for d in res.values())

    # top 2 stage-1 results, by total score across all tested services
    top2_names = sorted(all_results, key=lambda n: overall(all_results[n]), reverse=True)[:2]
    # recover (hkey, ikey) for each winner directly from stage1, not by
    # re-parsing the generated name — avoids ambiguity if a method key ever
    # contains "+" or "_"
    key_lookup = {name: (hkey, ikey) for name, hkey, ikey in stage1}

    stage2 = []
    for name in top2_names:
        hkey, ikey = key_lookup[name]
        stage2.extend(_stage2_refine(hkey, ikey))

    log(t(lang, "gen_stage2", count=len(stage2), winners=", ".join(top2_names)))
    for i, (name, h_method, i_method, cutoff) in enumerate(stage2, 1):
        if should_stop():
            break
        log(f"[{i}/{len(stage2)}] {name}")
        bat_text = build_bat_text_split(name, h_method, i_method, game_cutoff=cutoff)
        res = _test_candidate(version_dir, bat_text, targets, log, lang)
        if res:
            all_results[name] = res
            texts[name] = bat_text

    return all_results, texts


# --------------------------------------------------------------------------- #
# public entry point
# --------------------------------------------------------------------------- #

def run_generator(version_dir: Path, mode: str, targets=None, log=lambda m: None,
                   should_stop=lambda: False, lang="ru"):
    """Runs the generator and returns (all_results, best_per_service,
    overall_best, texts, baseline, inconclusive):
      - all_results/best_per_service/overall_best/texts: same shape as
        zapret_tester.run_tests() + summarize(), plus `texts` mapping
        candidate name -> generated .bat content (needed by
        save_candidate()/direct install, since candidates only ever exist
        as temp files during testing).
      - baseline: connectivity scores with no bypass running at all.
      - inconclusive: True if the best candidate didn't beat the baseline —
        i.e. the result doesn't actually demonstrate the bypass working.
    """
    if mode not in ("simple", "advanced"):
        raise ValueError(f"unknown generator mode: {mode}")

    targets = zt.TARGETS if targets is None else targets
    original_snapshot = zt.snapshot_winws()
    try:
        baseline = _measure_baseline(targets, log, lang)
        if should_stop():
            return {}, {}, None, {}, baseline, False
        if mode == "simple":
            all_results, texts = _run_simple(version_dir, targets, log, should_stop, lang)
        else:
            all_results, texts = _run_advanced(version_dir, targets, log, should_stop, lang)
    finally:
        zt.kill_winws()
        zt.restore_winws(original_snapshot)

    best_per_service, overall_best = zt.summarize(all_results)
    inconclusive = _is_inconclusive(baseline, overall_best)
    if inconclusive:
        log(t(lang, "gen_inconclusive_warning"))
    return all_results, best_per_service, overall_best, texts, baseline, inconclusive


def save_candidate(version_dir: Path, texts: dict, candidate_name: str, save_as: str) -> Path:
    """Persist a winning generated candidate as a normal strategy .bat file
    in the version folder, so it shows up like any other strategy afterwards
    (selectable for manual launch or `zapret_service.install_service`)."""
    if candidate_name not in texts:
        raise ValueError(f"unknown candidate: {candidate_name}")
    safe_name = save_as if save_as.lower().endswith(".bat") else f"{save_as}.bat"
    out_path = version_dir / safe_name
    out_path.write_text(texts[candidate_name], encoding="utf-8")
    return out_path
